# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vtnProveedor.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QSplitter, QStatusBar, QWidget)

class Ui_Proveedores(object):
    def setupUi(self, Proveedores):
        if not Proveedores.objectName():
            Proveedores.setObjectName(u"Proveedores")
        Proveedores.resize(602, 472)
        self.centralwidget = QWidget(Proveedores)
        self.centralwidget.setObjectName(u"centralwidget")
        self.splitter_2 = QSplitter(self.centralwidget)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setGeometry(QRect(240, 120, 311, 231))
        font = QFont()
        font.setFamilies([u"Times New Roman"])
        font.setPointSize(12)
        self.splitter_2.setFont(font)
        self.splitter_2.setOrientation(Qt.Vertical)
        self.txtnombre = QLineEdit(self.splitter_2)
        self.txtnombre.setObjectName(u"txtnombre")
        self.txtnombre.setFont(font)
        self.txtnombre.setMaxLength(50)
        self.splitter_2.addWidget(self.txtnombre)
        self.cbtipo = QComboBox(self.splitter_2)
        self.cbtipo.addItem("")
        self.cbtipo.addItem("")
        self.cbtipo.addItem("")
        self.cbtipo.addItem("")
        self.cbtipo.addItem("")
        self.cbtipo.setObjectName(u"cbtipo")
        self.cbtipo.setFont(font)
        self.splitter_2.addWidget(self.cbtipo)
        self.cbestado = QComboBox(self.splitter_2)
        self.cbestado.addItem("")
        self.cbestado.addItem("")
        self.cbestado.addItem("")
        self.cbestado.addItem("")
        self.cbestado.addItem("")
        self.cbestado.addItem("")
        self.cbestado.addItem("")
        self.cbestado.addItem("")
        self.cbestado.setObjectName(u"cbestado")
        self.cbestado.setFont(font)
        self.splitter_2.addWidget(self.cbestado)
        self.txtruc = QLineEdit(self.splitter_2)
        self.txtruc.setObjectName(u"txtruc")
        self.txtruc.setFont(font)
        self.txtruc.setMaxLength(13)
        self.splitter_2.addWidget(self.txtruc)
        self.txtcorreo = QLineEdit(self.splitter_2)
        self.txtcorreo.setObjectName(u"txtcorreo")
        self.txtcorreo.setFont(font)
        self.txtcorreo.setMaxLength(50)
        self.splitter_2.addWidget(self.txtcorreo)
        self.txttelefono = QLineEdit(self.splitter_2)
        self.txttelefono.setObjectName(u"txttelefono")
        self.txttelefono.setFont(font)
        self.txttelefono.setMaxLength(7)
        self.splitter_2.addWidget(self.txttelefono)
        self.txtdireccion = QLineEdit(self.splitter_2)
        self.txtdireccion.setObjectName(u"txtdireccion")
        self.txtdireccion.setFont(font)
        self.txtdireccion.setMaxLength(50)
        self.splitter_2.addWidget(self.txtdireccion)
        self.txtfecha = QLineEdit(self.splitter_2)
        self.txtfecha.setObjectName(u"txtfecha")
        self.txtfecha.setFont(font)
        self.txtfecha.setMaxLength(50)
        self.splitter_2.addWidget(self.txtfecha)
        self.splitter_3 = QSplitter(self.centralwidget)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setGeometry(QRect(70, 370, 481, 41))
        font1 = QFont()
        font1.setFamilies([u"Times New Roman"])
        font1.setPointSize(12)
        font1.setBold(True)
        self.splitter_3.setFont(font1)
        self.splitter_3.setOrientation(Qt.Horizontal)
        self.splitter_4 = QSplitter(self.splitter_3)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setFont(font1)
        self.splitter_4.setOrientation(Qt.Horizontal)
        self.splitter_5 = QSplitter(self.splitter_4)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setFont(font1)
        self.splitter_5.setOrientation(Qt.Horizontal)
        self.btnguardar = QPushButton(self.splitter_5)
        self.btnguardar.setObjectName(u"btnguardar")
        self.btnguardar.setFont(font1)
        self.splitter_5.addWidget(self.btnguardar)
        self.btnborrar = QPushButton(self.splitter_5)
        self.btnborrar.setObjectName(u"btnborrar")
        self.btnborrar.setFont(font1)
        self.splitter_5.addWidget(self.btnborrar)
        self.btnactualizar = QPushButton(self.splitter_5)
        self.btnactualizar.setObjectName(u"btnactualizar")
        self.btnactualizar.setFont(font1)
        self.splitter_5.addWidget(self.btnactualizar)
        self.btnlimpiar = QPushButton(self.splitter_5)
        self.btnlimpiar.setObjectName(u"btnlimpiar")
        self.btnlimpiar.setFont(font1)
        self.splitter_5.addWidget(self.btnlimpiar)
        self.splitter_4.addWidget(self.splitter_5)
        self.splitter_3.addWidget(self.splitter_4)
        self.splitter_6 = QSplitter(self.centralwidget)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setGeometry(QRect(70, 120, 161, 231))
        self.splitter_6.setFont(font1)
        self.splitter_6.setOrientation(Qt.Vertical)
        self.lbnombre = QLabel(self.splitter_6)
        self.lbnombre.setObjectName(u"lbnombre")
        self.lbnombre.setFont(font1)
        self.splitter_6.addWidget(self.lbnombre)
        self.lbtipo = QLabel(self.splitter_6)
        self.lbtipo.setObjectName(u"lbtipo")
        self.lbtipo.setFont(font1)
        self.splitter_6.addWidget(self.lbtipo)
        self.lbestado = QLabel(self.splitter_6)
        self.lbestado.setObjectName(u"lbestado")
        self.lbestado.setFont(font1)
        self.splitter_6.addWidget(self.lbestado)
        self.lbruc = QLabel(self.splitter_6)
        self.lbruc.setObjectName(u"lbruc")
        self.lbruc.setFont(font1)
        self.splitter_6.addWidget(self.lbruc)
        self.lbcorreo = QLabel(self.splitter_6)
        self.lbcorreo.setObjectName(u"lbcorreo")
        self.lbcorreo.setFont(font1)
        self.splitter_6.addWidget(self.lbcorreo)
        self.lbtelefono = QLabel(self.splitter_6)
        self.lbtelefono.setObjectName(u"lbtelefono")
        self.lbtelefono.setFont(font1)
        self.splitter_6.addWidget(self.lbtelefono)
        self.lbdireccion = QLabel(self.splitter_6)
        self.lbdireccion.setObjectName(u"lbdireccion")
        self.lbdireccion.setFont(font1)
        self.splitter_6.addWidget(self.lbdireccion)
        self.lbfecha = QLabel(self.splitter_6)
        self.lbfecha.setObjectName(u"lbfecha")
        self.lbfecha.setFont(font1)
        self.splitter_6.addWidget(self.lbfecha)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(70, 0, 421, 61))
        self.label_3.setFont(font1)
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(70, 80, 371, 27))
        self.splitter.setOrientation(Qt.Horizontal)
        self.lbbuscarruc = QLabel(self.splitter)
        self.lbbuscarruc.setObjectName(u"lbbuscarruc")
        self.lbbuscarruc.setFont(font1)
        self.splitter.addWidget(self.lbbuscarruc)
        self.txtbuscarruc = QLineEdit(self.splitter)
        self.txtbuscarruc.setObjectName(u"txtbuscarruc")
        self.txtbuscarruc.setMaxLength(13)
        self.splitter.addWidget(self.txtbuscarruc)
        self.btnbuscar = QPushButton(self.splitter)
        self.btnbuscar.setObjectName(u"btnbuscar")
        self.btnbuscar.setFont(font1)
        icon = QIcon()
        iconThemeName = u"system-search"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u"Proveedores/src/UI", QSize(), QIcon.Mode.Normal, QIcon.State.Off)

        self.btnbuscar.setIcon(icon)
        self.splitter.addWidget(self.btnbuscar)
        Proveedores.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(Proveedores)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 602, 21))
        Proveedores.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(Proveedores)
        self.statusbar.setObjectName(u"statusbar")
        Proveedores.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.txtnombre, self.cbtipo)
        QWidget.setTabOrder(self.cbtipo, self.cbestado)
        QWidget.setTabOrder(self.cbestado, self.txtruc)
        QWidget.setTabOrder(self.txtruc, self.txtcorreo)
        QWidget.setTabOrder(self.txtcorreo, self.txttelefono)
        QWidget.setTabOrder(self.txttelefono, self.txtdireccion)
        QWidget.setTabOrder(self.txtdireccion, self.txtfecha)
        QWidget.setTabOrder(self.txtfecha, self.btnguardar)
        QWidget.setTabOrder(self.btnguardar, self.btnborrar)
        QWidget.setTabOrder(self.btnborrar, self.btnactualizar)
        QWidget.setTabOrder(self.btnactualizar, self.btnlimpiar)

        self.retranslateUi(Proveedores)

        QMetaObject.connectSlotsByName(Proveedores)
    # setupUi

    def retranslateUi(self, Proveedores):
        Proveedores.setWindowTitle(QCoreApplication.translate("Proveedores", u"MainWindow", None))
        self.cbtipo.setItemText(0, QCoreApplication.translate("Proveedores", u"Seleccionar", None))
        self.cbtipo.setItemText(1, QCoreApplication.translate("Proveedores", u"Fabricante directo", None))
        self.cbtipo.setItemText(2, QCoreApplication.translate("Proveedores", u"Importador", None))
        self.cbtipo.setItemText(3, QCoreApplication.translate("Proveedores", u"Distribuidor mayorista", None))
        self.cbtipo.setItemText(4, QCoreApplication.translate("Proveedores", u"Distribuidor minorista", None))

        self.cbestado.setItemText(0, QCoreApplication.translate("Proveedores", u"Seleccionar", None))
        self.cbestado.setItemText(1, QCoreApplication.translate("Proveedores", u"Activo", None))
        self.cbestado.setItemText(2, QCoreApplication.translate("Proveedores", u"Inactivo", None))
        self.cbestado.setItemText(3, QCoreApplication.translate("Proveedores", u"Suspendido", None))
        self.cbestado.setItemText(4, QCoreApplication.translate("Proveedores", u"Bloqueado", None))
        self.cbestado.setItemText(5, QCoreApplication.translate("Proveedores", u"Pendiente", None))
        self.cbestado.setItemText(6, QCoreApplication.translate("Proveedores", u"Eliminado", None))
        self.cbestado.setItemText(7, QCoreApplication.translate("Proveedores", u"Archivado", None))

        self.btnguardar.setText(QCoreApplication.translate("Proveedores", u"Guardar", None))
        self.btnborrar.setText(QCoreApplication.translate("Proveedores", u"Borrar", None))
        self.btnactualizar.setText(QCoreApplication.translate("Proveedores", u"Actualizar", None))
        self.btnlimpiar.setText(QCoreApplication.translate("Proveedores", u"Limpiar", None))
        self.lbnombre.setText(QCoreApplication.translate("Proveedores", u"Nombre del Proveedor:", None))
        self.lbtipo.setText(QCoreApplication.translate("Proveedores", u"Tipo de Proveedor:", None))
        self.lbestado.setText(QCoreApplication.translate("Proveedores", u"Estado:", None))
        self.lbruc.setText(QCoreApplication.translate("Proveedores", u"Ruc:", None))
        self.lbcorreo.setText(QCoreApplication.translate("Proveedores", u"Correo:", None))
        self.lbtelefono.setText(QCoreApplication.translate("Proveedores", u"Tel\u00e9fono:", None))
        self.lbdireccion.setText(QCoreApplication.translate("Proveedores", u"Direcci\u00f3n:", None))
        self.lbfecha.setText(QCoreApplication.translate("Proveedores", u"Fecha de registro:", None))
        self.label_3.setText(QCoreApplication.translate("Proveedores", u"\n"
"SISTEMA DE GESTI\u00d3N DE PROVEEDORES", None))
        self.lbbuscarruc.setText(QCoreApplication.translate("Proveedores", u"Buscar por Ruc:", None))
        self.btnbuscar.setText(QCoreApplication.translate("Proveedores", u"Buscar", None))
    # retranslateUi

